SELECT
    RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, FV.FAVORITES
FROM REST_INFO RI
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE) FV
ON RI.FOOD_TYPE = FV.FOOD_TYPE AND RI.FAVORITES = FV.FAVORITES
ORDER BY FOOD_TYPE DESC;