WITH july_sum AS (
  SELECT FLAVOR, SUM(TOTAL_ORDER) AS july_total
  FROM JULY
  GROUP BY FLAVOR
)
SELECT f.FLAVOR
FROM FIRST_HALF f
LEFT JOIN july_sum j ON j.FLAVOR = f.FLAVOR
ORDER BY (f.TOTAL_ORDER + COALESCE(j.july_total, 0)) DESC
LIMIT 3;