SELECT
    GB.WRITER_ID,
    GU.NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD GB
JOIN USED_GOODS_USER GU
    ON GB.WRITER_ID = GU.USER_ID
WHERE
    GB.STATUS = 'DONE'
GROUP BY
    GB.WRITER_ID
HAVING
    SUM(GB.PRICE) >= 700000
ORDER BY
    TOTAL_SALES;