-- 조건 1) 보호 시작일보다 입양일이 더 빠른 동물
SELECT
    I.ANIMAL_ID, I.NAME
FROM 
    ANIMAL_INS I
JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE
    TIMESTAMPDIFF(SECOND, I.DATETIME, O.DATETIME) < 0
ORDER BY
    I.DATETIME;