-- join을 사용해서
SELECT
    COUNT(*) AS FISH_COUNT
FROM
    FISH_INFO I
JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
WHERE
    N.FISH_NAME IN ('BASS', 'SNAPPER');
    -- N.FISH_TYPE IN ('0', '1');
